# Generated by Django 6.0.4 on 2026-04-13 18:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_initial'),
        ('student', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('student', 'event')},
        ),
    ]
